# Generated by Django 4.0.3 on 2022-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
