# Generated by Django 4.0.3 on 2022-03-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_place_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Place_id',
            new_name='place_id',
        ),
        migrations.RenameField(
            model_name='place_type',
            old_name='Place_type_id',
            new_name='place_type_id',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Place',
            new_name='place',
        ),
    ]
