# Generated by Django 4.0.3 on 2022-03-26 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='id',
            new_name='review_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
