# Generated by Django 4.0.3 on 2022-03-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_rename_id_review_review_id_remove_message_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_image',
            new_name='room_image_1',
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
